# Generated by Django 4.1.2 on 2022-10-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonresponse',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='jsonresponse',
            name='task',
        ),
        migrations.RemoveField(
            model_name='jsonresponse',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='jsonresponse',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='jsonresponse',
            name='user',
        ),
        migrations.AddField(
            model_name='jsonresponse',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jsonresponse',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
