# Generated by Django 4.1.2 on 2022-10-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_description_jsonresponse_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonresponse',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
